image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.3"
  ANDROID_SDK_TOOLS: "4333796"
  ANDROID_HOME: "$CI_PROJECT_DIR/android-sdk-linux"
  ANDROID_SDK_ROOT: "$CI_PROJECT_DIR/android-sdk-linux"
  PROJECT_ACCESS_TOKEN: "$PROJECT_ACCESS_TOKEN"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -q -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

stages:
  - build
  - deploy
  - tag

# Job to build Javadoc
build_javadoc:
  stage: build
  script:
    - ./gradlew javadoc
  artifacts:
    paths:
      - sdk/build/docs/javadoc
  only:
    - master
    - dev

# Job to deploy Javadoc to GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Listing current directory"
    - ls -l
    - echo "Listing build/docs/javadoc directory"
    - ls -l sdk/build/docs/javadoc
    - mkdir -p public
    - cp -r sdk/build/docs/javadoc/* public/
    - echo "Listing public directory"
    - ls -l public
  artifacts:
    paths:
      - public
  only:
    - master
    - dev

# Original deploy job
deploy:
  stage: deploy
  script:
    - ./gradlew publish
  only:
    - master
    - dev

# Job to create a Git tag with the SDK version
create_tag:
  stage: tag
  before_script:
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
  script:
    - |
      sdkVersion=$(grep -E "sdkVersion = " sdk/build.gradle | cut -d '"' -f2)
      echo "Creating tag with SDK version: ${sdkVersion}"
      git tag -a "v${sdkVersion}" -m "Release ${sdkVersion}"
      git remote -v
      git remote set-url origin https://${PROJECT_ACCESS_TOKEN}@gitlab.com/wallee-payment/device-software/com.wallee.android.till.sdk.git
      git remote -v
      git push origin "v${sdkVersion}"
  dependencies: []
