package com.wallee.android.till.sdk;

/**
 * The type of message being sent.
 */
public enum ApiMessageType {
    CHECK_API_SERVICE_COMPATIBILITY,
    SDK_VERSION_NOT_SUPPORTED_REPLY,
    AUTHORIZE_TRANSACTION,
    COMPLETE_TRANSACTION,
    CANCEL_LAST_TRANSACTION_OPERATION,
    VOID_TRANSACTION,
    EXECUTE_SUBMISSION,
    EXECUTE_TRANSMISSION,
    EXECUTE_FINAL_BALANCE,
    SEND_LOG_LINE,
    GENERATE_PANTOKEN,
    GET_PINPAD_INFORMATION,
    EXECUTE_CONFIGURATION,
    EXECUTE_INITIALISATION
}
