package com.wallee.android.till.sdk;

/**
 * The type of message being sent.
 */
public enum ApiMessageType {
    GET_SERVICE_API_SDK_VERSION,
    SDK_VERSION_NOT_SUPPORTED_REPLY,
    AUTHORIZE_TRANSACTION,
    COMPLETE_TRANSACTION,
    CANCEL_LAST_TRANSACTION_OPERATION,
    VOID_TRANSACTION,
    EXECUTE_SUBMISSION,
    EXECUTE_TRANSMISSION,
    EXECUTE_FINAL_BALANCE,
}
